[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "importer"
version = "0.9.30"
edition = "2021"

[[bin]]
name = "plato-importer"
path = "src/main.rs"


[dependencies]
core = { path = "../core" }
getopts = "0.2.21"

